# Generated by Django 5.0.7 on 2024-07-24 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_taskdetails_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='category',
            field=models.CharField(blank=True, default='Personal', max_length=50, null=True),
        ),
    ]
