# Generated by Django 5.0.7 on 2024-07-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_taskdetails_creation_date_alter_taskdetails_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdetails',
            unique_together={('username', 'title', 'description')},
        ),
    ]
